<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>RIBBENÅS French Door Fridge/Freezer | IKEA 700</title>
  <meta name="description" content="RIBBENÅS French door fridge/freezer, IKEA 700 freestanding in black stainless steel, with 347 l fridge and 169 l freezer volume.">
  <meta name="keywords" content="RIBBENÅS, IKEA fridge freezer, French door fridge, black stainless steel fridge">
  <meta property="og:title" content="RIBBENÅS French Door Fridge/Freezer | IKEA 700">
  <meta property="og:description" content="A spacious black stainless steel French door fridge/freezer for food lovers and large households.">
  <meta property="og:type" content="product">
  <meta property="og:image" content="https://www.ikea.com/au/en/images/products/ribbenas-french-door-fridge-freezer-ikea-700-freestanding-black-stainless-steel__1354033_pe952442_s5.jpg?f=xl">
  <meta name="theme-color" content="#f6f3ee">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Manrope:wght@400;500;600;700;800&family=Playfair+Display:wght@600;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="style.css">
  <script type="application/ld+json">
  {
    "@context":"https://schema.org", "@type":"Product", "name":"RIBBENÅS French door fridge/freezer",
    "image":["https://www.ikea.com/au/en/images/products/ribbenas-french-door-fridge-freezer-ikea-700-freestanding-black-stainless-steel__1354033_pe952442_s5.jpg?f=xl"],
    "description":"RIBBENÅS French door fridge/freezer, IKEA 700 freestanding in black stainless steel, with 347 l fridge and 169 l freezer volume.",
    "brand":{"@type":"Brand","name":"IKEA"}, "sku":"00580773",
    "offers":{"@type":"Offer","priceCurrency":"AUD","price":"1614.15","availability":"https://schema.org/InStock"}
  }
  </script>
</head>
<body>
  <div class="announcement"><span>🔥 Limited Time Offer — 30% OFF + Free Shipping</span><span class="countdown" aria-label="Offer countdown"><b id="days">03</b>d <b id="hours">11</b>h <b id="minutes">42</b>m <b id="seconds">08</b>s</span></div>
  <header class="site-header">
    <a class="logo" href="#home" aria-label="Pulse One home"><span class="logo-mark">P</span>pulse<span>one</span></a>
    <button class="menu-toggle" aria-label="Open navigation" aria-expanded="false">☰</button>
    <nav class="main-nav" aria-label="Main navigation">
      <a href="#home">Home</a><a href="#product">Product</a><a href="#features">Features</a><a href="#reviews">Reviews</a><a href="#faq">FAQ</a><a href="#contact">Contact</a>
    </nav>
  </header>

  <main id="home">
    <section class="hero section" id="product">
      <div class="hero-copy reveal"><p class="eyebrow">01 / Everyday intelligence</p><h1>Your everyday<br><em>health,</em> beautifully<br>in sync.</h1><p class="hero-lede">The smart fitness watch that keeps up with your ambition — from your first step to your deepest sleep.</p><a class="text-link" href="#details">Discover the details <span>↘</span></a></div>
      <div class="product-visual reveal">
        <div class="image-frame"><img id="main-product-image" src="https://www.ikea.com/au/en/images/products/ribbenas-french-door-fridge-freezer-ikea-700-freestanding-black-stainless-steel__1354033_pe952442_s5.jpg?f=xl" alt="RIBBENÅS black stainless steel French door fridge/freezer" fetchpriority="high"><span class="image-label">RIBBENÅS / 005.807.73</span></div>
        <div class="thumbs" role="list" aria-label="Product image gallery">
          <button class="thumb active" data-image="https://www.ikea.com/au/en/images/products/ribbenas-french-door-fridge-freezer-ikea-700-freestanding-black-stainless-steel__1354033_pe952442_s5.jpg?f=xl" aria-label="View RIBBENÅS front"><img src="https://www.ikea.com/au/en/images/products/ribbenas-french-door-fridge-freezer-ikea-700-freestanding-black-stainless-steel__1354033_pe952442_s5.jpg?f=xl" alt=""></button>
          <button class="thumb" data-image="https://www.ikea.com/au/en/images/products/ribbenas-french-door-fridge-freezer-ikea-700-freestanding-black-stainless-steel__1341641_pe948861_s5.jpg?f=xl" aria-label="View RIBBENÅS interior"><img src="https://www.ikea.com/au/en/images/products/ribbenas-french-door-fridge-freezer-ikea-700-freestanding-black-stainless-steel__1341641_pe948861_s5.jpg?f=xl" alt=""></button>
          <button class="thumb" data-image="https://www.ikea.com/au/en/images/products/ribbenas-french-door-fridge-freezer-ikea-700-freestanding-black-stainless-steel__1337612_pe947946_s5.jpg?f=xl" aria-label="View RIBBENÅS storage"><img src="https://www.ikea.com/au/en/images/products/ribbenas-french-door-fridge-freezer-ikea-700-freestanding-black-stainless-steel__1337612_pe947946_s5.jpg?f=xl" alt=""></button>
          <button class="thumb" data-image="https://www.ikea.com/au/en/images/products/ribbenas-french-door-fridge-freezer-ikea-700-freestanding-black-stainless-steel__1337619_pe947958_s5.jpg?f=xl" aria-label="View RIBBENÅS detail"><img src="https://www.ikea.com/au/en/images/products/ribbenas-french-door-fridge-freezer-ikea-700-freestanding-black-stainless-steel__1337619_pe947958_s5.jpg?f=xl" alt=""></button>
          <button class="thumb" data-image="https://www.ikea.com/au/en/images/products/ribbenas-french-door-fridge-freezer-ikea-700-freestanding-black-stainless-steel__1337629_pe947966_s5.jpg?f=xl" aria-label="View RIBBENÅS freezer"><img src="https://www.ikea.com/au/en/images/products/ribbenas-french-door-fridge-freezer-ikea-700-freestanding-black-stainless-steel__1337629_pe947966_s5.jpg?f=xl" alt=""></button>
          <button class="thumb" data-image="https://www.ikea.com/au/en/images/products/ribbenas-french-door-fridge-freezer-ikea-700-freestanding-black-stainless-steel__1337650_pe947988_s5.jpg?f=xl" aria-label="View RIBBENÅS display"><img src="https://www.ikea.com/au/en/images/products/ribbenas-french-door-fridge-freezer-ikea-700-freestanding-black-stainless-steel__1337650_pe947988_s5.jpg?f=xl" alt=""></button>
          <button class="thumb" data-image="https://www.ikea.com/au/en/images/products/ribbenas-french-door-fridge-freezer-ikea-700-freestanding-black-stainless-steel__1337638_pe947974_s5.jpg?f=xl" aria-label="View RIBBENÅS design"><img src="https://www.ikea.com/au/en/images/products/ribbenas-french-door-fridge-freezer-ikea-700-freestanding-black-stainless-steel__1337638_pe947974_s5.jpg?f=xl" alt=""></button>
        </div>
      </div>
      <div class="purchase-panel reveal"><p class="eyebrow">Pulse One</p><h2>Premium Smart<br>Fitness Watch</h2><div class="rating"><span class="stars">★★★★★</span> <strong>4.8</strong> <a href="#reviews">(1,248 reviews)</a></div><p class="price"><del>₹4,999</del> <strong>₹2,999</strong> <span>40% OFF</span></p><p class="stock"><i></i> In stock <small>• Ships today</small></p><p class="product-desc">A calm, capable companion for the way you move. Track your heart, sleep, workouts and more with a full week of battery life.</p><div class="buy-row"><a class="btn btn-coral" href="https://www.ikea.com/au/en/p/ribbenas-french-door-fridge-freezer-ikea-700-freestanding-black-stainless-steel-00580773/" target="_blank" rel="noopener">grab this <span>↗</span></a></div><div class="promise-grid"><div>⌁ <span>Free shipping<br><small>Across India</small></span></div><div>▣ <span>Secure payment<br><small>100% protected</small></span></div><div>↩ <span>1-year warranty<br><small>Money-back guarantee</small></span></div></div></div>
    </section>

    <section class="feature-strip" id="features"><div class="section feature-inner"><div><p class="eyebrow">The Pulse promise</p><h2>Made for your<br><em>whole</em> life.</h2></div><div class="feature-grid"><article><span>✦</span><h3>Premium quality</h3><p>Aircraft-grade aluminium, made to last.</p></article><article><span>↗</span><h3>Fast delivery</h3><p>At your door in 2–5 working days.</p></article><article><span>⌁</span><h3>Easy returns</h3><p>30 days to change your mind.</p></article><article><span>◷</span><h3>1-year warranty</h3><p>Expert support, whenever you need it.</p></article></div></div></section>

    <section class="details section" id="details"><div class="section-heading"><p class="eyebrow">02 / In the details</p><h2>Everything you need.<br><em>Nothing you don't.</em></h2></div><div class="details-layout"><div class="detail-intro"><p>Pulse One makes the data that matters feel effortless. A bright, edge-to-edge display, thoughtful health insights and a design you will want to wear all day.</p><div class="benefit-list"><div><b>01</b><span><strong>Know your body</strong>Continuous heart rate, SpO₂ and sleep tracking.</span></div><div><b>02</b><span><strong>Move with purpose</strong>100+ workout modes with real-time coaching.</span></div><div><b>03</b><span><strong>Stay in your flow</strong>Smart notifications without the noise.</span></div></div></div><div class="tabs"><div class="tab-buttons" role="tablist"><button class="tab-button active" data-tab="specs">Specifications</button><button class="tab-button" data-tab="included">What's included</button><button class="tab-button" data-tab="warranty">Warranty</button></div><div class="tab-panel active" id="specs"><div><span>Display</span><b>1.78” AMOLED · 60Hz</b></div><div><span>Materials</span><b>Aluminium alloy · Silicone</b></div><div><span>Dimensions</span><b>44 × 38 × 10.5 mm</b></div><div><span>Weight</span><b>38g with strap</b></div><div><span>Battery</span><b>Up to 7 days</b></div><div><span>Water resistance</span><b>5 ATM</b></div></div><div class="tab-panel" id="included"><p>Pulse One watch, magnetic charging cable, two-size silicone strap, quick start guide and warranty card.</p></div><div class="tab-panel" id="warranty"><p>Every Pulse One includes a 1-year limited warranty and a 30-day no-questions-asked return window.</p></div></div></div></section>

    <section class="how section"><div class="section-heading centered"><p class="eyebrow">03 / Simple by design</p><h2>Good things come<br><em>in three steps.</em></h2></div><div class="steps"><article><span class="step-no">01</span><div class="step-icon">◌</div><h3>Choose your product</h3><p>Pick your colour, set your quantity and make it yours.</p></article><article><span class="step-no">02</span><div class="step-icon">→</div><h3>Place your order</h3><p>Checkout in under a minute with a payment method you trust.</p></article><article><span class="step-no">03</span><div class="step-icon">⌁</div><h3>Receive your product</h3><p>Unbox a calmer, more capable way to move through your day.</p></article></div></section>

    <section class="reviews-section" id="reviews"><div class="section reviews-inner"><div class="review-summary"><p class="eyebrow">04 / Kind words</p><h2>Loved by<br><em>1,248</em> movers.</h2><div class="big-rating"><strong>4.8</strong><span><span class="stars">★★★★★</span><small>Based on 1,248 reviews</small></span></div><div class="slider-controls"><button id="prev-review" aria-label="Previous review">←</button><button id="next-review" aria-label="Next review">→</button></div></div><div class="review-window"><div class="review-track" id="review-track"><article class="review-card"><span class="quote">“</span><p>It has made my mornings so much more intentional. The sleep insights are surprisingly accurate, and it looks gorgeous with everything.</p><footer><img src="https://i.pravatar.cc/80?img=47" alt="Ananya Mehta"><span><strong>Ananya Mehta</strong><small>Verified buyer · 12 June 2025</small></span><b>★★★★★</b></footer></article><article class="review-card"><span class="quote">“</span><p>Finally, a fitness watch that doesn't feel like a tiny computer strapped to my wrist. Battery lasts all week. An easy five stars.</p><footer><img src="https://i.pravatar.cc/80?img=12" alt="Rohan Kapoor"><span><strong>Rohan Kapoor</strong><small>Verified buyer · 04 June 2025</small></span><b>★★★★★</b></footer></article><article class="review-card"><span class="quote">“</span><p>The display is incredibly crisp and the strap is comfortable even during long runs. Pulse One gets the important things right.</p><footer><img src="https://i.pravatar.cc/80?img=32" alt="Mira Shah"><span><strong>Mira Shah</strong><small>Verified buyer · 28 May 2025</small></span><b>★★★★★</b></footer></article></div></div></div></section>

    <section class="faq section" id="faq"><div class="section-heading"><p class="eyebrow">05 / Good to know</p><h2>Questions,<br><em>answered.</em></h2></div><div class="faq-list"><details open><summary>What is the delivery time? <span>+</span></summary><p>Orders are dispatched the same day and usually arrive within 2–5 working days across India.</p></details><details><summary>Is shipping free? <span>+</span></summary><p>Yes. Standard shipping is free on every Pulse One order, with no minimum purchase.</p></details><details><summary>What payment methods are accepted? <span>+</span></summary><p>We accept Cash on Delivery, UPI, and all major credit and debit cards through this demo checkout.</p></details><details><summary>Can I return the product? <span>+</span></summary><p>Absolutely. You have 30 days from delivery to request a return, provided the watch is in its original condition.</p></details><details><summary>Is there a warranty? <span>+</span></summary><p>Pulse One comes with a 1-year limited warranty covering manufacturing defects.</p></details><details><summary>How can I track my order? <span>+</span></summary><p>Once your order ships, we will email your tracking link and delivery updates.</p></details></div></section>

    <section class="cta section" id="contact"><div><p class="eyebrow">Your next chapter</p><h2>Ready to<br><em>upgrade?</em></h2><p>Order today and get 40% off plus free shipping.</p></div><a class="btn btn-coral" href="https://www.ikea.com/au/en/p/ribbenas-french-door-fridge-freezer-ikea-700-freestanding-black-stainless-steel-00580773/" target="_blank" rel="noopener">grab this <span>↗</span></a></section>
  </main>

  <div class="trust-bar"><span>🔒 Secure checkout</span><span>🚚 Fast delivery</span><span>↩ Easy returns</span><span>✓ Verified product</span><span>💳 Secure payment</span></div>
  <footer class="site-footer"><div><a class="logo" href="#home"><span class="logo-mark">P</span>pulse<span>one</span></a><p>Your everyday health,<br>beautifully in sync.</p></div><div><h3>Explore</h3><a href="#product">Product</a><a href="#features">Features</a><a href="#reviews">Reviews</a></div><div><h3>Support</h3><a href="#faq">FAQ</a><a href="#contact">Contact us</a><a href="#">Shipping & returns</a></div><div><h3>Say hello</h3><a href="mailto:hello@pulseone.in">hello@pulseone.in</a><a href="tel:+918001234567">+91 800 123 4567</a><div class="socials"><a href="#" aria-label="Instagram">◎</a><a href="#" aria-label="Twitter">𝕏</a><a href="#" aria-label="Facebook">f</a></div></div><div class="footer-bottom"><span>© 2025 Pulse One. All rights reserved.</span><span><a href="#">Privacy</a> · <a href="#">Terms</a> · <a href="#">Refund policy</a></span></div></footer>

  <script src="script.js" defer></script>
</body>
</html>
